### ISSUE TITLE
Error: Create Artifact Container failed

### ISSUE THREAD

**Issue by yaeda** [veracode/veracode-sca#36]
I have been running scans weekly, but from this week, the actions have been failing.
Although the execution of Actions fails, the upload of scan results is successful.
Do you know what the cause is?

Log

```
Run veracode/veracode-sca@v2.1.10
Start command
curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan .  
Scan finished with exit code:  0
Store json Results as Artifact
Starting artifact upload
For more detailed logs during the artifact upload process, enable step-debugging: https://docs.github.com/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging
Artifact name is valid!
The file has been saved!
Create Artifact Container - Error is not retryable
##### Begin Diagnostic HTTP information #####
Status Code: 400
Status Message: Bad Request
Header Information: {
  "content-length": "268",
  "content-type": "application/json; charset=utf-8",
  "date": "Fri, 07 Feb 2025 09:37:37 GMT",
  "server": "Kestrel",
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "143eb534-66c2-48d2-ac7b-bbf25d33c28c",
  "activityid": "30e219fa-fb7c-46f6-ba96-58c886d110c5",
  "x-tfs-session": "30e219fa-fb7c-46f6-ba96-58c886d110c5",
  "x-vss-e2eid": "30e219fa-fb7c-46f6-ba96-58c886d110c5",
  "x-vss-senderdeploymentid": "6074703f-c195-632a-bd61-21691fc86fa5",
  "x-frame-options": "SAMEORIGIN"
}
###### End Diagnostic HTTP information ######
##### Begin Diagnostic HTTP information #####
Status Code: 400
Status Message: Bad Request
Header Information: {
  "content-length": "268",
  "content-type": "application/json; charset=utf-8",
  "date": "Fri, 07 Feb 2025 09:37:37 GMT",
  "server": "Kestrel",
  "cache-control": "no-store,no-cache",
  "pragma": "no-cache",
  "strict-transport-security": "max-age=2592000",
  "x-tfs-processid": "143eb534-66c2-48d2-ac7b-bbf25d33c28c",
  "activityid": "30e219fa-fb7c-46f6-ba96-58c886d110c5",
  "x-tfs-session": "30e219fa-fb7c-46f6-ba96-58c886d110c5",
  "x-vss-e2eid": "30e219fa-fb7c-46f6-ba96-58c886d110c5",
  "x-vss-senderdeploymentid": "6074703f-c195-632a-bd61-21691fc86fa5",
  "x-frame-options": "SAMEORIGIN"
}
###### End Diagnostic HTTP information ######
/home/runner/work/_actions/veracode/veracode-sca/v2.1.10/dist/index.js:1191
            throw Error(`${name} failed: ${customErrorInformation}`);
                  ^

Error: Create Artifact Container failed: The artifact name Veracode Agent Based SCA Results is not valid. Request URL https://pipelinesghubeus4.actions.githubusercontent.com/xfAkhTsdHSlALB8ffvaj0TASTW8Frt3U2VkYN8Yfvqp9V2WUzd/_apis/pipelines/workflows/13197130632/artifacts?api-version=6.0-preview
    at /home/runner/work/_actions/veracode/veracode-sca/v2.1.10/dist/index.js:1191:19
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/veracode/veracode-sca/v2.1.10/dist/index.js:1139:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.18.0
```

Script

```yaml
jobs:
  veracode-sca-task:
    name: Scan repository with Veracode SCA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: false
```
